apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      volumes:
        - name: config
          configMap:
            name: hellok8s-config
      containers:
        - image: guangzhengli/hellok8s:v4
          name: hellok8s-container
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hellok8s-config
                  key: MESSAGE