apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodeployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: hellodeployment
  template:
    metadata:
      labels:
        app: hellodeployment
    spec:
      containers:
        - name: hellodeployment-container
          image: guangzhengli/busybox:v2
