apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
    - port: 4567
      nodePort: 30001

# kubectl exec -it hellok8s-7f4c57d446-7j6rd -- sh
# curl http://hellok8s-svc:4567
# env | grep HELLOK8S
# curl $HELLOK8S_SVC_SERVICE_HOST:$HELLOK8S_SVC_SERVICE_PORT